# Generated by Django 3.2.9 on 2021-12-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0003_alter_restaurant_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='name',
            new_name='DishName',
        ),
        migrations.RenameField(
            model_name='dishcategory',
            old_name='name',
            new_name='CategoryName',
        ),
        migrations.RenameField(
            model_name='dishimage',
            old_name='name',
            new_name='ImgName',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='DistrictName',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='RestorantName',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='name',
            new_name='SectorName',
        ),
    ]
