# Generated by Django 3.2.9 on 2021-12-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0004_auto_20211201_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Restaurants', to='Resto.district'),
            preserve_default=False,
        ),
    ]
